apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openldap-secrets
  namespace: openldap
spec:
  encryptedData:
    LDAP_ADMIN_PASSWORD: AgAIp56S9RwRPWyvyHCg5qQvwJNv2rTU3HmuS3uAupRugMBVctDj64YHtLTew656EiJ4wsXFI6HfdAosOQAIT5pZ+VkZEFxciKCrPmbIV64vuITEFbpxYszD7n27uYOzQDIKpJar5qzCta+XNfjwtWwlvDBiER+5PhgpFlfjOVNY/qFHHD3qDg0u00AQAwKRJXvpWjQ70nuaT06OUZYhDU04+2WqJkf6/shd5m5bPhHxDYCd1skLrGv8QbUEs7p6vDPu1+GRx84PpD/gLfZb/orioaK1h38HEW2iBVhthbs4MOJTs8AvXqljfz4axbat2RRDvIqZKVMHgRV/IVc8w19H9KJ8iq95piFpeCHs093mWBAY7GPenGvyrpAwJLo6fh85CYKqSJOcXBjtv19ozh5K27XB/ERN4oVKvVFaODeDql+EBUcHDOOXqGytpQ6pMpPlU6pxuA18NzmksvxnaRtohsZZXWT2PlhN9Ol8S0y7VkpsTD4T1omjMRSedzxsU1p6dkAo1B6BU4esPFZ9of1WZfPAyBNVHAUdncdLwocvX6MmHxGZoXvxdgtwqgzOtg8mcmLB/SvmfEeZDwTLiCW/+Chp3ZBz2hiFs+PbhyUiftAsT1s90UzKExYvjC1LglkVYKY8H7WOaKJYrYwbMPAAMOyxsuXy2bxAYJ8VNhpNj5WinAvviv33mY3PhLDs3jMe9uNt1Q==
  template:
    metadata:
      name: openldap-secrets
      namespace: openldap
    type: Opaque
