apiVersion: v1
kind: Service
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
spec:
  type: ClusterIP
  ports:
    - name: ldap
      port: 389
      targetPort: 389
      protocol: TCP
    - name: ldaps
      port: 636
      targetPort: 636
      protocol: TCP
  selector:
    app: openldap
  clusterIP: None
