apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  namespace: openldap
  labels:
    app: openldap
spec:
  serviceName: openldap
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
    spec:
      containers:
      - name: openldap
        image: osixia/openldap:1.5.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: openldap-env
        - secretRef:
            name: openldap-secrets
        ports:
        - name: ldap
          containerPort: 389
          protocol: TCP
        - name: ldaps
          containerPort: 636
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /var/lib/ldap
        - name: config
          mountPath: /etc/ldap/slapd.d
        livenessProbe:
          tcpSocket:
            port: ldap
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          tcpSocket:
            port: ldap
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: config
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: local-path
      resources:
        requests:
          storage: 256Mi
