apiVersion: v1
kind: Service
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  selector:
    app: authentik-postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
